### PR TITLE
Wider navbar problem solved

### PR DESCRIPTION
**Pull request by FranciscoLira**

### CODE REVIEW

**Comment by FranciscoLira** [comment]
@joao-coelho This was the solution that I found! Do you think is a good one?

**Comment by nelsonmestevao** [comment]
2019-01-29-113132_503x372_scrot
It is not a perfect solution

**Review by nelsonmestevao — CHANGES_REQUESTED** [review]
2019-01-29-113132_503x372_scrot
It is not a perfect solution :point_up:

**Comment by FranciscoLira** [comment]
@nelsonmestevao how have you done that? Tried now in different computers and didn't get that error.

**Review by nelsonmestevao — APPROVED** [review]

**Pull request merged**
