### PR TITLE
I18n (PT and EN)

### PR DESCRIPTION
**Pull request by joao-coelho**
- add i18n, with implementation examples using past speakers, workshops, activities,...
- add year variable to make annual updates easier
- update README

### CODE REVIEW

**Review by nelsonmestevao — APPROVED** [review]
Nice job :rocket:

**Comment by joao-coelho** [comment]
É melhor esperar pelas alterações da @mariajbp antes de fazer merge.

**Review by nelsonmestevao — APPROVED** [review]
Agenda not working

**Review by nelsonmestevao — CHANGES_REQUESTED** [review]
Agenda not working

**Pull request closed without merging**
