### PR TITLE
Fix initial slider in agenda

### PR DESCRIPTION
**Pull request by nelsonmestevao**
Slide show starts at 0 and goes until the last until the last one. For now, this will work. I am not sure about the future tough. Read more about this JS library [here](http://kenwheeler.github.io/slick/).

### CODE REVIEW

**Review by catarinamachado — CHANGES_REQUESTED** [review]
Monday will be:
-> initialSlide: 0 - 5 = -5 ----> ERROR, calendar will not appear

I guess the best option (if anyone want to resolve this in a good way) is change initialSlide variable to "day - 6" today (saturday), "day - 7" tomorrow (sunday) and on monday we put only "initialSlide: day" and in the rest of the week everything will work ok

**Comment by nelsonmestevao** [comment]
> Monday will be:
> -> initialSlide: 0 - 5 = -5 ----> ERROR, calendar will not appear
> 
> I guess the best option (if anyone want to resolve this in a good way) is change initialSlide variable to "day - 6" today (saturday), "day - 7" tomorrow (sunday) and on monday we put only "initialSlide: day" and in the rest of the week everything will work ok

I don't think Monday will have any issue. It will display just fine. I just test it manually and the focus is on Monday. 

PS: Monday is 4.

**Comment by catarinamachado** [comment]
According to this link: https://www.w3schools.com/jsref/jsref_getday.asp, monday it's 1, and I think that's why website doesn't work now

**Comment by nelsonmestevao** [comment]
@catarinamachado you are completely right. See my most recent commit. I don't find this an elegant solution but I think now it is right.

**Review by catarinamachado — APPROVED** [review]

**Comment by catarinamachado** [comment]
I think it's perfect!

**Comment by nelsonmestevao** [comment]
I just cleaned it a bit :+1:

**Pull request merged**
